### ISSUE TITLE
При открытии сделок появляются стрелочки, показывающие цену открытия и закрытия сделки, в дальнейшем они мешают анализу, тем что закрывают собой бары

### ISSUE THREAD

**Issue by CasperAndrey** [kamalligator/VSATester#10]
![image](https://user-images.githubusercontent.com/37226732/59629947-b747f880-914c-11e9-82af-a02b6ada740b.png)

**Comment by CasperAndrey** [comment]
Можно их не убирать но сделать так чтобы они были кликабельны и их можно было удалять по желанию пользователя

**Comment by kamalligator** [comment]
> Можно их не убирать но сделать так чтобы они были кликабельны и их можно было удалять по желанию пользователя

Сделать опцию показывать сделки на графике?

**Comment by CasperAndrey** [comment]
По моему это и есть отображение сделок на графике, я имел ввиду после когда сделка закрывается стрелки остаются, и их невозможно удалить, так вот это и хотелось бы улучшить чтобы была возможность их удалить. Кому-то они возможно не мешают а тем кто побарно смотрит и важно закрытие и открытие бара видеть то они значительно мешают

**Comment by kamalligator** [comment]
> По моему это и есть отображение сделок на графике, я имел ввиду после когда сделка закрывается стрелки остаются, и их невозможно удалить, так вот это и хотелось бы улучшить чтобы была возможность их удалить. Кому-то они возможно не мешают а тем кто побарно смотрит и важно закрытие и открытие бара видеть то они значительно мешают

Ок, сделаем

**Comment by kamalligator** [comment]
Сделано
