### ISSUE TITLE
Не ошибка а предложение по улучшению работы тестера

### ISSUE THREAD

**Issue by CasperAndrey** [kamalligator/VSATester#11]
Суть в том что когда работаешь с клавишами "пауза\пуск" во вкладки "настройка" сама вкладка в низу экрана занимает значительная пространство, мое предложение такое, чтобы перенести именно сами кнопки вверх. Как показано на рисунке 
![image](https://user-images.githubusercontent.com/37226732/59636523-63dda680-915c-11e9-8251-c5b68b0d4130.png)
И затем при сворачивании нижней вкладки у нас появиться значительно больше пространства и график более читабельным. А возможность управления останется прежней. 
![image](https://user-images.githubusercontent.com/37226732/59636648-ae5f2300-915c-11e9-87e7-7369b929bd50.png)

**Comment by CasperAndrey** [comment]
Дополнение. Я понимаю что можно свернуть и сделать что-то вроде вот так. но все ровно немного места экономиться. 
![image](https://user-images.githubusercontent.com/37226732/59636723-e9f9ed00-915c-11e9-974b-f3f88558f536.png)

**Comment by kamalligator** [comment]
Сделано

**Comment by Dibashir** [comment]
Добавьте пожалуйста для рисования Вертикальную линию
