### ISSUE TITLE
Последняя версия 28.06.2019 - Версия 1.0.5

### ISSUE THREAD

**Issue by kamalligator** [kamalligator/VSATester#13]
**64 бит:** https://drive.google.com/open?id=1EiMLnOzugyajYHPZYkBqQskMnUSY3o4L
**32 бит:** https://drive.google.com/open?id=1KpfZfPwkvs4DDTposrK-cUu7f1gSTR1i

Исправлен баг, при котором при переключении тф стетала точная дата
Поправлены траблы со скроллом
Исправлены проблемы отрисовки в таблице сделок
Добавлена версия и autoupdate

**28.06.2019 - Версия 1.0.5**
Добавлена вертикальная линия
Исправлен баг с потерей точной даты на всех тф

**Comment by CasperAndrey** [comment]
Спасибо за доработки)
