### ISSUE TITLE
Более глобальный запрос. 

### ISSUE THREAD

**Issue by CasperAndrey** [kamalligator/VSATester#15]
Просьба такая, наверное многие да и сам Александр Сошников, использует в работе несколько таймфреймов. Обычно анализируют старшие ТМ D1, H1 и затем спускаются на мелкие ТМ для поиска точки входа на  М15,, М5, М1, Просьба такова возможно ли сделать несколько окон с одновременной отрисовкой цены на разных ТМ. После этого создастся впечатление реальной торговли в реальном времени где ты будешь видеть все зоны и главные уровни на часовом ТМ и одновременно поиск точки на младших ТМ. Пример как я торгую в МТ4 
![image](https://user-images.githubusercontent.com/37226732/60063431-8d22a780-9705-11e9-85a1-a6554a30fa47.png)
Буду очень благодарен за эту работу и также такое дополнение сделает тестер значительно лучше чем другие подобные тестеры, например тот же тестер в МТ4 который не имеет такой функции

**Comment by Dibashir** [comment]
Хотел тоже эту тему поднять, а тут уже написали )

**Comment by CasperAndrey** [comment]
Ну как идет работа над моей просьбой? будете добавлять функционал?

**Comment by kamalligator** [comment]
В ближайшей версии выйдут отложенные ордера, в последующей версии планирую Ваш запрос

**Comment by CasperAndrey** [comment]
ок спс
6

**Comment by kamalligator** [comment]
Решено в версии 1.1
