### ISSUE TITLE
Здравствуйте! Вчера была активирована программа. Все работало. Закрыв программу на час при использовании выдается сообщение что недействительна лицензия. А при попытке заново зарегистрироваться пешет что лицензия уже используется

### ISSUE THREAD

**Issue by sergeybaln76** [kamalligator/VSATester#18]
Здравствуйте! Вчера была активирована программа. Все работало. Закрыв программу на час при использовании выдается сообщение что недействительна лицензия. А при попытке заново зарегистрироваться пешет что лицензия уже используется

**Comment by sergeybaln76** [comment]
Здравствуйте! Вчера была активирована программа. Все работало. Закрыв программу на час при использовании выдается сообщение что недействительна лицензия. А при попытке заново зарегистрироваться пешет что лицензия уже используется

**Comment by kamalligator** [comment]
Добрый день! Попробуйте зарегистрировать еще раз. После регистрации перезапустите тестер

**Comment by sergeybaln76** [comment]
Многократно пробовал. Последний раз долько что. Каждый раз одно и тоже - лицензия недействительна, а ключ активации используется другим пользователем


>Вторник, 17 сентября 2019, 13:17 +03:00 от kamalligator <notifications@github.com>:
>
>Добрый день! Попробуйте зарегистрировать еще раз. После регистрации перезапустите тестер
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Сергей Балныков

**Comment by kamalligator** [comment]
Попрбуйте сейчас

**Comment by sergeybaln76** [comment]
все нормально спасибо!


>Вторник, 17 сентября 2019, 13:24 +03:00 от kamalligator <notifications@github.com>:
>
>Попрбуйте сейчас
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Сергей Балныков
