### ISSUE TITLE
расширение области графика

### ISSUE THREAD

**Issue by alexgherco** [kamalligator/VSATester#2]
- Использую гор. объемы возможно ли добавить эти гор. объемы на историю?
- Возможно ли расширение области графика:
![image](https://user-images.githubusercontent.com/2143904/58370663-c94dc700-7f11-11e9-918a-bd66f1734cd4.png)

**Comment by alexgherco** [comment]
Евро грузится только до 5 марта:
![image](https://user-images.githubusercontent.com/2143904/58372286-f86d3400-7f23-11e9-8538-a6e217f84480.png)
В ближайшее время история по всем инструментам будет дополнена

**Comment by alexgherco** [comment]
при установке выбрана опция "для всех", но при запуске требуется админский пароль - это не совсем правильно.

**Comment by kamalligator** [comment]
> * Использую гор. объемы возможно ли добавить эти гор. объемы на историю?
> * Возможно ли расширение области графика:
>   ![image](https://user-images.githubusercontent.com/2143904/58370663-c94dc700-7f11-11e9-918a-bd66f1734cd4.png)

Просьба вынести запрос по горизонтальным вопросам в отдельный топик.
По расщирению области графика: опишите, пожалуйста, по шагам порядок действий, приведший к такому результату, я не смог это воспроизвести

**Comment by kamalligator** [comment]
> при установке выбрана опция "для всех", но при запуске требуется админский пароль - это не совсем правильно.

Принято

**Comment by alexgherco** [comment]
По **расширению** области графика:

1. первоначальный вид после загрузки значений:
![image](https://user-images.githubusercontent.com/2143904/58379326-a6232600-7faa-11e9-99ca-171025c7bb3d.png)

2. после скрытия панелей
![image](https://user-images.githubusercontent.com/2143904/58379315-7a07a500-7faa-11e9-9237-04254ac54e93.png)

кстати, auto hide нижней панели не срабатывает

**Comment by kamalligator** [comment]
Странно,  у меня auto hide работает. Auto hide должен срабатывать при наведении мышки на закладку. И почему остальных закладок во вкладке торговля не хватает
![image](https://user-images.githubusercontent.com/37157267/58385779-fbd0f000-7ff5-11e9-97c3-f42271da73f0.png)
Можно с Вами по тимвьюверу связаться? Так я быстрее смогу понять в чем проблема

**Comment by kamalligator** [comment]
> при установке выбрана опция "для всех", но при запуске требуется админский пароль - это не совсем правильно.

Исправлено в последней версии
