### ISSUE TITLE
Индикация значений цены и временной шкалы

### ISSUE THREAD

**Issue by alexgherco** [kamalligator/VSATester#5]
Как включить индикацию значений например, текущей цены.
![image](https://user-images.githubusercontent.com/2143904/58379780-fa310900-7fb0-11e9-84d5-ff7f6d6367b0.png)

**Comment by kamalligator** [comment]
На данный момент нет отображения текущей цены, но если нажать левую кнопку мыши и удерживать ее появляется всплывающее окно, в котором видно все значения на текущем баре. Таким образом чтобы посмотреть текущую цену достаточно нажать и удерживать левую кнопку мыши на последнем баре.
