### ISSUE TITLE
Добрый день помогите решить вопрос вчера оплатил тестер выкл ключ а программа выдаёт лицензионный ключ недействителен что делать?

### ISSUE THREAD

**Issue by krusb** [kamalligator/VSATester#7]
Добрый день помогите решить вопрос вчера оплатил тестер ввёл ключ а программа выдаёт лицензионный ключ недействителен что делать?

_Originally posted by @krusb in https://github.com/kamalligator/VSATester/issues/1#issuecomment-497284316_

**Comment by kamalligator** [comment]
Добрый день, Вы вчера уже регистрировались? Я вижу что лицензия была активирована в 23.30

**Comment by kamalligator** [comment]
> Добрый день помогите решить вопрос вчера оплатил тестер ввёл ключ а программа выдаёт лицензионный ключ недействителен что делать?
> 
> _Originally posted by @krusb in [#1 (comment)](https://github.com/kamalligator/VSATester/issues/1#issuecomment-497284316)_

Добрый день, Вы вчера уже регистрировались? Я вижу, что лицензия была активирована в 23.30

**Comment by kamalligator** [comment]
Поробуйте еще раз зарегистрировать.
После регистрации перезапустите программу

**Comment by krusb** [comment]
Программа проработала полчаса и произошла ошибка теперь опять выдаёт лицензия недействительна что делать винда 10 32 битная антивирус аваст помогите(((((

**Comment by kamalligator** [comment]
Я Вам отправил на почту свой скайп, пишите, будем разбираться

**Comment by krusb** [comment]
Да всё верно я зарегистрировался но выдаёт ошибку 

Отправлено из мобильной Почты Mail.Ru

четверг, 30 мая 2019 г., 13:37 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by krusb** [comment]
Всё получилось всем спасибо заработало

Отправлено из мобильной Почты Mail.Ru

четверг, 30 мая 2019 г., 19:00 +0300 от KRusb  <krusb@mail.ru>:

**Comment by krusb** [comment]
Пробовал все заново решился программу переустанавливал ноутбук перезагружал не помогает винда 10 32 битная может с ней чего не так

Отправлено из мобильной Почты Mail.Ru

четверг, 30 мая 2019 г., 15:40 +0300 от notifications@github.com  <notifications@github.com>:
