### ISSUE TITLE
При увеличении масштаба исчезают бары которые справа.

### ISSUE THREAD

**Issue by CasperAndrey** [kamalligator/VSATester#9]
![image](https://user-images.githubusercontent.com/37226732/59627920-0b9ca980-9148-11e9-98d0-ee7a60aa2b07.png)
   ![image](https://user-images.githubusercontent.com/37226732/59627854-dee89200-9147-11e9-88e3-e256126dc2a8.png)

**Comment by kamalligator** [comment]
Сделано
